app:
  title: "AI-Powered Fabric Recommender"
  subtitle: "Dissertation Project — University of West London"
  theme_color: "#1F4E79"

datasets:
  literature_url: "https://raw.githubusercontent.com/Volandofernando/Material-Literature-data-/main/Dataset.xlsx"
  survey_url: "https://raw.githubusercontent.com/Volandofernando/REAL-TIME-Dataset/main/IT%20Innovation%20in%20Fabric%20Industry%20%20(Responses).xlsx"

model:
  n_estimators: 300
  random_state: 42
  test_size: 0.25

features:
  moisture_regain: ["moisture", "regain"]
  water_absorption: ["water", "absorption"]
  drying_time: ["drying", "time"]
  thermal_conductivity: ["thermal", "conductivity"]

target_keywords: ["comfort", "score"]
